In [2]:
import torch 

In [3]:
def activation(x):
    return 1/(1+torch.exp(-x))

In [4]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

In [5]:
output=activation(torch.sum(features*weights)+bias)

In [6]:
activation(torch.mm(features, weights.view(5,1))+bias)

tensor([[0.1595]])

In [7]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [8]:
activation(torch.mm(activation(torch.mm(features,W1)+B1),W2)+B2)

tensor([[0.3171]])

**NumPy to Torch and back**

In [9]:
import numpy as np

In [11]:
a=np.random.rand(4,3)
a

array([[0.155939  , 0.25812257, 0.63675082],
       [0.25322637, 0.20077895, 0.56891712],
       [0.80555135, 0.37923106, 0.68737714],
       [0.76292283, 0.99124704, 0.93802198]])

In [12]:
b=torch.from_numpy(a)
b

tensor([[0.1559, 0.2581, 0.6368],
        [0.2532, 0.2008, 0.5689],
        [0.8056, 0.3792, 0.6874],
        [0.7629, 0.9912, 0.9380]], dtype=torch.float64)

In [13]:
b.numpy()

array([[0.155939  , 0.25812257, 0.63675082],
       [0.25322637, 0.20077895, 0.56891712],
       [0.80555135, 0.37923106, 0.68737714],
       [0.76292283, 0.99124704, 0.93802198]])

In [14]:
b.mul_(2)

tensor([[0.3119, 0.5162, 1.2735],
        [0.5065, 0.4016, 1.1378],
        [1.6111, 0.7585, 1.3748],
        [1.5258, 1.9825, 1.8760]], dtype=torch.float64)

In [15]:
a

array([[0.31187801, 0.51624514, 1.27350164],
       [0.50645274, 0.40155789, 1.13783424],
       [1.6111027 , 0.75846213, 1.37475429],
       [1.52584566, 1.98249408, 1.87604396]])